#!/usr/bin/env python3
"""
sync_plan.py -- the prose plan and the executable plan cannot drift.

`docs/ACTION_PLAN.md` is the plan a human reads; `state/backlog.json` is the plan
the loop executes. If they disagree, a session trusting one is misled by the
other. This tool makes disagreement a CI failure.

    python tools/sync_plan.py check     exit 1 and say what differs
    python tools/sync_plan.py write     regenerate the task index in the doc

What "in agreement" means, exactly:

1. **Phases.** Every backlog phase appears in the doc as a heading
   `## PHASE <id> — <title>`, in order, with the same title, and the doc has no
   phase the backlog lacks. An italic aside at the end of a heading, such as
   `*(the most important artefact)*`, is commentary and is ignored.
2. **Tasks.** The doc ends with a task index between two marker lines. It is
   generated from the backlog -- id, title and dependencies for every task,
   grouped by phase -- and must be byte-identical to what `write` would produce.
   Status is deliberately left out, so finishing a task does not churn the doc;
   `python tools/loop.py status` is where status lives.

Standard library only.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC = os.path.join(ROOT, "docs", "ACTION_PLAN.md")
BACKLOG = os.path.join(ROOT, "state", "backlog.json")

BEGIN = "<!-- BEGIN TASK INDEX: generated by tools/sync_plan.py write; do not edit by hand -->"
END = "<!-- END TASK INDEX -->"
HEADING = re.compile(r"^## PHASE (\d+) — (.+?)\s*$")
ASIDE = re.compile(r"\s*\*\(.*\)\*\s*$")


def _read(path):
    with open(path, "r", encoding="utf-8") as fh:
        return fh.read()


def normalise(title):
    return ASIDE.sub("", title).strip()


def doc_phases(text):
    out = []
    for line in text.splitlines():
        m = HEADING.match(line)
        if m:
            out.append((int(m.group(1)), normalise(m.group(2))))
    return out


def render_index(backlog):
    lines = [BEGIN, "", "## Task index", "",
             "Generated from `state/backlog.json`. Status is not shown here: run "
             "`python tools/loop.py status`.", ""]
    for phase in sorted(backlog["phases"], key=lambda p: p["id"]):
        lines.append("### Phase %s — %s" % (phase["id"], phase["title"]))
        lines.append("")
        for t in backlog["tasks"]:
            if t["phase"] != phase["id"]:
                continue
            deps = ", ".join("`%s`" % d for d in t.get("depends_on") or [])
            lines.append("- `%s` %s%s" % (t["id"], t["title"],
                                          (" — after %s" % deps) if deps else ""))
        lines.append("")
    lines.append(END)
    return "\n".join(lines) + "\n"


def split_doc(text):
    """Return (prose, index) where index is the marker block or None."""
    if BEGIN not in text:
        return text, None
    head, rest = text.split(BEGIN, 1)
    if END not in rest:
        return head, BEGIN + rest
    block, tail = rest.split(END, 1)
    return head + tail.lstrip("\n"), BEGIN + block + END + "\n"


def check(doc_text, backlog):
    problems = []
    want = [(p["id"], p["title"]) for p in sorted(backlog["phases"], key=lambda p: p["id"])]
    prose, index = split_doc(doc_text)
    have = doc_phases(prose)
    want_ids = [i for i, _ in want]
    have_ids = [i for i, _ in have]
    for pid, title in want:
        match = [t for i, t in have if i == pid]
        if not match:
            problems.append("phase %s (%s) is in the backlog but has no '## PHASE %s' "
                            "heading in the doc" % (pid, title, pid))
        elif match[0] != title:
            problems.append("phase %s is titled '%s' in the doc but '%s' in the backlog"
                            % (pid, match[0], title))
    for pid in have_ids:
        if pid not in want_ids:
            problems.append("the doc has a PHASE %s heading the backlog does not know" % pid)
    if len(set(have_ids)) != len(have_ids):
        problems.append("the doc repeats a phase heading")
    if [i for i in have_ids if i in want_ids] != sorted(i for i in have_ids if i in want_ids):
        problems.append("the doc's phase headings are out of order")
    expected = render_index(backlog)
    if index is None:
        problems.append("the doc has no task index; run: python tools/sync_plan.py write")
    elif index != expected:
        problems.append("the task index is stale or hand-edited; run: "
                        "python tools/sync_plan.py write")
    return problems


def write(doc_path=DOC, backlog_path=BACKLOG):
    backlog = json.loads(_read(backlog_path))
    prose, _ = split_doc(_read(doc_path))
    text = prose.rstrip("\n") + "\n\n---\n\n" if not prose.rstrip().endswith("---") \
        else prose.rstrip("\n") + "\n\n"
    text += render_index(backlog)
    with open(doc_path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    return text


def main(argv):
    cmd = argv[0] if argv else "check"
    if cmd == "write":
        write()
        print("task index regenerated in %s" % os.path.relpath(DOC, ROOT))
        cmd = "check"
    if cmd == "check":
        backlog = json.loads(_read(BACKLOG))
        problems = check(_read(DOC), backlog)
        if problems:
            print("PLAN SYNC CHECK FAILED (%d)" % len(problems))
            for p in problems:
                print("  - %s" % p)
            return 1
        print("plan sync check passed: %d phases and %d tasks agree between "
              "docs/ACTION_PLAN.md and state/backlog.json."
              % (len(backlog["phases"]), len(backlog["tasks"])))
        return 0
    print(__doc__)
    return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
